### ISSUE TITLE
kobuki_msgs missing

### ISSUE THREAD

**Issue by ahasenfr** [intel/ros_moving_object#2]
Contradictory to the ReadMe 6.2, the kobuki_msgs are apparently no more part of the full-desktop-install of ROS. At least not for Kinetic which I have installed. Tried to find them, but they were not installed. And so I got a corresponding error.
Had downloaded the source from github and put it in my package. That worked, don't know if you guys want to do a better solution....

EDIT:
as I've learned now, kobuki_msgs was never part of any of the official ROS metapackages.
But your description in the ReadMe make it seem like it would be.
Could you adjust that please?

**Comment by LewisLiuPub** [comment]
Thank you very much for your reporting.
I am coming to update ReadMe.

**Comment by LewisLiuPub** [comment]
the ReadMe has been updated for the issue.
Close it, please feel free to share comments if any more.
